### ISSUE TITLE
Unexpected behaviour for add_violin

### ISSUE THREAD

**Issue by johnny101er** [jbengler/tidyplots#14]
Hi Jan,

Thanks for developing tidy plots. I'm playing around to get used to it and ran into unexpected behaviour for the violin plot. The data I'm plotting has a lowest value of 79. The violin plots touch the bottom of the y-axis seemingly indicating there are values lower than 79.
all_data %>% 
  tidyplot(x=treat, y=area, colour=treat) %>% 
  add_violin(scale = "count") %>% 
  reorder_x_axis_labels("norm", "c", "cd", "cdr") %>% 
  adjust_y_axis(limits =  c(0,250)) %>% 
  adjust_size(100, 100) 
![image](https://github.com/user-attachments/assets/0fd7189a-e116-4e76-8e17-07780f7905de)

If I plot using ggplot, the bottom of the violin plots stop at the expected value
area_violin <- ggplot(all_data[all_data$area > 50,], aes(x=treat, y=area, fill = treat)) +
  geom_violin(scale = "count") +
  scale_x_discrete(limits = c("norm", "c", "cd", "cdr")) +
  coord_cartesian(ylim = c(0,250)) +
  ggtitle(paste("ggplot, violin")) +
  theme_bw()
![image](https://github.com/user-attachments/assets/6538f7e8-3541-496a-91c9-3495b9b14917)

Plotting the data points individually in tidy plots indicates that the minimum data points is 79.
all_data %>% 
  tidyplot(x=treat, y=area, colour=treat) %>% 
  add_data_points_beeswarm(alpha = 0.4) %>% 
  reorder_x_axis_labels("norm", "c", "cd", "cdr") %>% 
  adjust_y_axis(limits =  c(0,250)) %>% 
  adjust_size(100, 100) 
![image](https://github.com/user-attachments/assets/abdeaa2a-f130-4f9a-b8ae-24cc5a49a418)

Any help or explanation is appreciated.
Best,
Johnny

**Comment by jbengler** [comment]
Hi @johnny101er 

Thank you for using tidyplots!

My guess is that you are looking for the `trim` argument of `add_violin()`.

### `trim = FALSE` (tidyplots default)
<img width="579" alt="Bildschirmfoto 2024-11-29 um 22 04 52" src="https://github.com/user-attachments/assets/885dc87e-953f-4f18-a41c-1c360127bc43">

### `trim = TRUE` (ggplot2 default)
<img width="582" alt="Bildschirmfoto 2024-11-29 um 22 05 05" src="https://github.com/user-attachments/assets/9ad673a9-81ca-4ee9-9685-ce1aa5289083">

Best
Jan

**Comment by johnny101er** [comment]
I guess the behaviour was expected! Thanks for pointing that out for me.
Best,
Johnny
