### ISSUE TITLE
Add color scheme `colors_discrete_alger`

### ISSUE THREAD

**Issue by jbengler** [jbengler/tidyplots#18]
Suggested by @loukesio

<img width="403" alt="Bildschirmfoto 2024-12-04 um 23 39 51" src="https://github.com/user-attachments/assets/e9ab7d87-f512-42fd-8678-a5f2648459d0">

**Comment by jbengler** [comment]
@loukesio

Are you maybe willing to make a pull request? You would only have to touch `R/tidycolor.R`

**Comment by loukesio** [comment]
sure sure thank you for thinking about it. I ll do it tomorrow evening :)
