### ISSUE TITLE
Consider putting CRAN or GH link in abstract

### ISSUE THREAD

**Issue by rmflight** [jbengler/tidyplots#2]
I saw the biorxiv preprint, but there was no link to either the CRAN or GitHub.

Felt odd for a preprint describing a software library.

**Comment by jbengler** [comment]
Thank you for the suggestion!

I included the links in the abstract of an updated version of the preprint. This is currently being processed by biorxiv and should be online soon.

**Comment by jbengler** [comment]
The new version in now online at https://www.biorxiv.org/content/10.1101/2024.11.08.621836v2

However, the links are not rendered as hyperlinks but plain text.

@rmflight Do you know a special trick how to get clickable links in the bioRxiv abstract?

**Comment by jbengler** [comment]
It took bioRxiv a while to update the abstract with the information extracted from the PDF. Now the links are functional.
