### ISSUE TITLE
Error in Ops

### ISSUE THREAD

**Issue by ZhWKang** [jbengler/tidyplots#3]
Hello, I encountered an error when trying to use the tidyplots.
Code:
```
study %>%
  tidyplot(x = treatment, y = score) %>%
  add_data_points() %>%
  add_mean_dash() %>%
  add_sem_errorbar()
```
Error Message:
Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames

**Comment by jbengler** [comment]
Hi @ZhWKang, thank you for using tidyplots!

I can not reproduce the error when running your code. However, I found this ggplot2 issue that might solve the problem.
https://github.com/tidyverse/ggplot2/issues/5619

**Comment by ZhWKang** [comment]
Thank you @jbengler ！The issue is solved after updating patchwork to latest version.

**Comment by jbengler** [comment]
That is great to hear!
