### ISSUE TITLE
split_plot incompabilities 

### ISSUE THREAD

**Issue by jlhelling** [jbengler/tidyplots#30]
Hi,
tidyplots is **awesome** and the `split_plot()` function works pretty well! However, it resets modifications like titles or legend positions. For instance:

-     Titles added with add_title() are removed.
-     Legend positions modified with adjust_legend_position() are reverted to the default (e.g., placed to the right).

The **documentation** suggests these changes can be reapplied using ggplot2-style theming, but attempts to do so (e.g., `theme(legend.position = "bottom")` do not work as expected. Additionally, the documentation mentions that examples should demonstrate how to reapply these customizations after _split_plot()_, but no such examples are currently provided. 

> guides - A string specifying how guides should be treated in the layout. 'collect' will collect guides below to the given nesting level, removing duplicates. 'keep' will stop collection at this level and let guides be placed alongside their plot. auto will allow guides to be collected if a upper level tries, but place them alongside the plot if not. If you modify default guide "position" with [theme(legend.position=...)](https://ggplot2.tidyverse.org/reference/theme.html) while also collecting guides you must apply that change to the overall patchwork (see example).

Here a **reprex** for my issue:

```
library(tidyplots)
library(tidyverse)

# Simulated example dataset
set.seed(123)
data <- data.frame(
  date = seq(from = as.Date("2021-01-01"), to = as.Date("2021-12-31"), by = "month"),
  NDWI = runif(12, 0, 1),
  DW = runif(12, 0, 1),
  combined = runif(12, 0, 1),
  month = month(seq(from = as.Date("2021-01-01"), to = as.Date("2021-12-31"), by = "month")),
  Class = sample(c("Urban", "Rural"), 12, replace = TRUE)
)

# Create a histogram function
histoplots <- function(data, split_var, title_plot) {
  plot <- data |>
    pivot_longer(cols = c("NDWI", "DW", "combined"), names_to = "index", values_to = "value") |>
    mutate(index = as.factor(index), month = month(date, label = TRUE)) |>
    tidyplot(y = value, fill = index) |>
    add_title(title_plot) |>
    add_histogram(binwidth = 0.05, position = "dodge") |>
    adjust_legend_position(position = "bottom") |> 
    theme_minimal_y() |> 
    split_plot(
      by = split_var,
      ncol = 4,
      nrow = 3
    )
  
  # Attempt to reposition legend after split_plot()
  plot <- plot |> add(ggplot2::theme(legend.position = "bottom")) 
  
  return(plot)
}


# Generate histogram
title_plot <- "Example: Adjusting Title and Legend Position"
split_var <- "month"
histogram_plot <- histoplots(data, split_var, title_plot)


# Display the plot
histogram_plot
```

**Comment by jbengler** [comment]
Hi @jlhelling 

Thank you for using tidyplots!

Unfortunately, what you are attempting to do cannot be done within tidyplots. However, since all tidyplots are `patchwork` objects you can do the following.

```
p1 <- 
  study %>% 
  tidyplot(x = dose, y = score, color = dose) %>% 
  add_mean_bar() %>% 
  split_plot(by = group) +
  patchwork::plot_annotation(title = "Example: Adjusting Title and Legend Position") &
  ggplot2::theme(legend.position = "bottom")

p1

p1 %>% save_plot("trash_me.png")
```

Caution: because you have to use the `+` and `&`operators, the resulting object can no longer be directly piped into a down-stream function like `save_plot()`. Instead, you have to assign the plot to a variable (e.g. p1) and then pipe this into `save_plot()`.

Best
Jan

**Comment by jlhelling** [comment]
Hi Jan,
Thank you so much, that works very well !

**Comment by jlhelling** [comment]
Hello Jan,
unfortunately I can't solve another problem now. I want to split my plot into twelve groups and show 4 plots per page, but the automatic multi-paging doesn't seem to work. I would like to have only 4 plots per page and thus create a total of 3 pages. Here you have an example:

```
p1 <- 
  climate %>% 
  tidyplot(x = year, y = avg_temperature) %>% 
  add_data_points() %>% 
  split_plot(by = month, ncol = 1, nrow = 4, widths = 100) +
  patchwork::plot_annotation(title = "Example: Adjusting Title and Legend Position") &
  ggplot2::theme(legend.position = "bottom")

p1
```

**Comment by jbengler** [comment]
Hey @jlhelling 

Now it gets even more complicated. When you do a split to multiple pages you end up with a `list` of `patchwork` objects. Thus, you have to loop over them to modify each of them. This should work.

```
p1 <- 
  climate %>% 
  tidyplot(x = year, y = avg_temperature) %>% 
  add_data_points() %>% 
  split_plot(by = month, ncol = 1, nrow = 4, widths = 100)

p1 <- 
  purrr::map(p1, function(x) {
    x +
      patchwork::plot_annotation(title = "Example: Adjusting Title and Legend Position") &
  ggplot2::theme(legend.position = "bottom")
  })

p1
```

Best
Jan

**Comment by jlhelling** [comment]
I see, thank you so much Jan! 
Best, 
Leo
