### ISSUE TITLE
Pictures look small using RStudio 

### ISSUE THREAD

**Issue by trafficfan** [jbengler/tidyplots#31]
![QQ20241217-175333](https://github.com/user-attachments/assets/70af4f3b-982a-40ba-8735-53cb61de6478)
The ggplot2 pictures look normal while sth may got wrong with tidyplots

**Comment by jbengler** [comment]
Hi @trafficfan 

Thank you for using tidyplots!

Have a look at this Discussion: https://github.com/jbengler/tidyplots/discussions/26

Best
Jan
