### ISSUE TITLE
Support statistical annotation for grouped plots

### ISSUE THREAD

**Issue by LeiGuo0812** [jbengler/tidyplots#4]
Hi,
I sincerely appreciate the `tidyplots` package. It's a fantastic tool for creating beautiful and tidy plots efficiently.

I particularly like the `stat_pvalue_manual` function in the `ggpubr` package, which is great for handling complex grouped or faceted plots. However, it seems that the current `add_test_pvalue` function in `tidyplots` only supports statistical tests for a single factor.

I tried using the add function to directly apply the `stat_pvalue_manual`, but encountered some errors. Is it possible to enhance `tidyplots` to support more complex grouped or faceted plots? Or is there currently a workaround for these scenarios?

Below are the test codes I used:

```r
library(ggpubr)
library(rstatix)
library(tidyplots)

df <- ToothGrowth
df$dose <- as.factor(df$dose)
head(df, 3)

stat.test <- stat.test <- df %>%
  group_by(dose) %>%
  t_test(len ~ supp) %>%
  add_xy_position(x = "dose", dodge = 0.8)
  
stat.test2 <- df %>%
  t_test(len ~ dose) %>% 
  add_xy_position(x = "dose")

stat.test3 <- df %>%
  group_by(supp) |> 
  t_test(len ~ dose) %>% 
  add_xy_position(x = "dose", group = 'supp')

# it worked fine for ggplot
ggplot(df, aes(x = dose, y = len, color = supp)) +
  geom_boxplot() +
  stat_pvalue_manual(
    stat.test,  label = "p", tip.length = 0
  ) +
  stat_pvalue_manual(
    stat.test2,  label = "p", tip.length = 0.02,
    step.increase = 0.05
  ) +
  stat_pvalue_manual(
    stat.test3,  label = "p", tip.length = 0.02,
    step.increase = 0.05, step.group.by = 'supp'
  )

# but get error when using tidyplots
tidyplot(df, x = dose, y = len, color = supp)  |> 
  add_boxplot() |> 
  add(add_pvalue(
    stat.test,  label = "p", tip.length = 0
  ))  |>
  add(stat_pvalue_manual(
    stat.test2,  label = "p", tip.length = 0.02,
    step.increase = 0.05
  ))  |>
  add(stat_pvalue_manual(
    stat.test3,  label = "p", tip.length = 0.02,
    step.increase = 0.05, step.group.by = 'supp'
  ))

#Error:
#! Problem while computing aesthetics.
#ℹ Error occurred in the 2nd layer.
#Caused by error:
#! can not find object 'supp'
```

Thank you so much for your hard work on this amazing package, and I really look forward to your response!

**Comment by jbengler** [comment]
Hi @LeiGuo0812 

Thank you for using tidyplots!

Your error occurs because 'ggpubr::stat_pvalue_manual()' fails when both 'color' and 'fill' aesthetics are provided.
I can replicate the issue in your ggplot2 code by adding 'fill = supp' and fix it in tidyplots by setting 'fill = NA'. See the example below.

A bit of background: tidyplots automatically assigns the same variable to both 'color' and 'fill' unless explicitly specified otherwise.

Best
Jan

```
# adding aes(fill = supp) breaks the ggplot
# does not work
ggplot(df, aes(x = dose, y = len, color = supp, fill = supp)) +
  geom_boxplot() +
  stat_pvalue_manual(
    stat.test,  label = "p", tip.length = 0
  ) +
  stat_pvalue_manual(
    stat.test2,  label = "p", tip.length = 0.02,
    step.increase = 0.05
  ) +
  stat_pvalue_manual(
    stat.test3,  label = "p", tip.length = 0.02,
    step.increase = 0.05, step.group.by = 'supp'
  )

# adding aes(fill = NA) rescues the tidyplot
# just works
tidyplot(df, x = dose, y = len, color = supp, fill = NA) %>% 
  add_boxplot() %>% 
  add(stat_pvalue_manual(
    stat.test,  label = "p", tip.length = 0
  )) %>%
  add(stat_pvalue_manual(
    stat.test2,  label = "p", tip.length = 0.02,
    step.increase = 0.05
  )) %>% 
  add(stat_pvalue_manual(
    stat.test3,  label = "p", tip.length = 0.02,
    step.increase = 0.05, step.group.by = 'supp'
  ))
```

**Comment by jbengler** [comment]
Unfortunately not. In an attempt to keep things simple, the mappings in tidyplots are restricted to the `tidyplot()` call.

Since the error also occurs in plain ggplot2 + ggpubr, one could report this issue in ggpubr. Maybe they are able to fix it for all ggpubr users.

**Comment by jbengler** [comment]
I opened this ggpubr issue https://github.com/kassambara/ggpubr/issues/621

**Comment by jbengler** [comment]
Hi @LeiGuo0812 

I just learned that providing `inherit.aes = FALSE` to your `stat_pvalue_manual()` calls should solve your problem.

```
tidyplot(df, x = dose, y = len, color = supp)  |>
  add_boxplot() |>
  add(stat_pvalue_manual(
    stat.test,  label = "p", tip.length = 0,
    inherit.aes = FALSE
  ))  |>
  add(stat_pvalue_manual(
    stat.test2,  label = "p", tip.length = 0.02,
    step.increase = 0.05, inherit.aes = FALSE
  ))  |>
  add(stat_pvalue_manual(
    stat.test3,  label = "p", tip.length = 0.02,
    step.increase = 0.05, step.group.by = 'supp',
    inherit.aes = FALSE
  ))
```

See also: https://github.com/kassambara/ggpubr/issues/621#issuecomment-2850311530

**Comment by LeiGuo0812** [comment]
> Hi   你好[@LeiGuo0812](https://github.com/LeiGuo0812)
> 
> I just learned that providing `inherit.aes = FALSE` to your `stat_pvalue_manual()` calls should solve your problem.我刚刚了解到，为您的 `stat_pvalue_manual()` 调用提供 `inherit.aes = FALSE` 应该可以解决您的问题。
> 
> ```
> tidyplot(df, x = dose, y = len, color = supp)  |>
>   add_boxplot() |>
>   add(stat_pvalue_manual(
>     stat.test,  label = "p", tip.length = 0,
>     inherit.aes = FALSE
>   ))  |>
>   add(stat_pvalue_manual(
>     stat.test2,  label = "p", tip.length = 0.02,
>     step.increase = 0.05, inherit.aes = FALSE
>   ))  |>
>   add(stat_pvalue_manual(
>     stat.test3,  label = "p", tip.length = 0.02,
>     step.increase = 0.05, step.group.by = 'supp',
>     inherit.aes = FALSE
>   ))
> ```
> 
> See also: [kassambara/ggpubr#621 (comment)](https://github.com/kassambara/ggpubr/issues/621#issuecomment-2850311530)  另请参阅： [kassambara/ggpubr#621 (comment)](https://github.com/kassambara/ggpubr/issues/621#issuecomment-2850311530)

Excellent solution! Thanks a lot!😄

**Comment by LeiGuo0812** [comment]
> Hi [@LeiGuo0812](https://github.com/LeiGuo0812)
> 
> I just learned that providing `inherit.aes = FALSE` to your `stat_pvalue_manual()` calls should solve your problem.
> 
> ```
> tidyplot(df, x = dose, y = len, color = supp)  |>
>   add_boxplot() |>
>   add(stat_pvalue_manual(
>     stat.test,  label = "p", tip.length = 0,
>     inherit.aes = FALSE
>   ))  |>
>   add(stat_pvalue_manual(
>     stat.test2,  label = "p", tip.length = 0.02,
>     step.increase = 0.05, inherit.aes = FALSE
>   ))  |>
>   add(stat_pvalue_manual(
>     stat.test3,  label = "p", tip.length = 0.02,
>     step.increase = 0.05, step.group.by = 'supp',
>     inherit.aes = FALSE
>   ))
> ```
> 
> See also: [kassambara/ggpubr#621 (comment)](https://github.com/kassambara/ggpubr/issues/621#issuecomment-2850311530)

Excellent solution! Thanks a lot!😄

**Comment by jbengler** [comment]
You are welcome!
