### ISSUE TITLE
tidyplots on R v4.2.2

### ISSUE THREAD

**Issue by m3i-ltroxler** [jbengler/tidyplots#5]
Hello,
I just discovered the biorxiv preprint and would like to install the package tidyplots on my working R version 4.2.2 but I get the warning : package 'tidyplots' is not available for this version of R. I did not find in the documentation any limitation on the use of R 4.x.x. Is there another solution then upgrading R ? 
I am using RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Ubuntu Jammy and the 2.0.0 version of tidyverse.
I look forward to seeing your impressive work and await your reply.

**Comment by m3i-ltroxler** [comment]
Following your link on Stackoverflow I was able to install tidyplots by adding the devtools and Cairo packages. But now following your vignette instructions, when I try the command line: study %>%  tidyplot(x = treatment, y = score)
I get the following error: Error in ggplot2::scale_y_continuous(name = title, breaks = breaks, labels = labels,  : 
  unused argument (transform = transform)
 I am using the 3.4.1 version of ggplot2
 
If you want to reproduce the error you may use my Dockerfile:
FROM rocker/rstudio:4.2.2 

ARG bioc_ver=3.16

RUN apt-get clean all && \
    apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y \
        libhdf5-dev \
        libcurl4-gnutls-dev \
        libssl-dev \
        libxml2-dev \
        libpng-dev \
        libxt-dev \
        zlib1g-dev \
        libbz2-dev \
        liblzma-dev \
        libglpk40 \
        libgit2-dev \
        libcairo2-dev \
        libjpeg-dev \
        libtiff-dev \
        libglib2.0-dev \
   && apt-get clean all && \
    apt-get purge && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Verify Cairo installation
RUN R -e "capabilities()[['cairo']]"

RUN Rscript -e "install.packages(c('rmarkdown', 'tidyverse', 'workflowr', 'BiocManager', 'dplyr', 'gplots', 'devtools'));"

RUN Rscript -e "BiocManager::install(version = '${bioc_ver}')"
RUN R -e 'BiocManager::install(ask = F)' && R -e 'BiocManager::install(c("AnnotationForge", "Biobase", "biomaRt", "Biostrings", "DESeq2", \
 "IRange", ask = F))'
RUN R -e 'devtools::install_github("jbengler/tidyplots", ask = F)'

COPY --chown=rstudio:rstudio Rprofile /home/rstudio/.Rprofile

WORKDIR /home/rstudio

**Comment by m3i-ltroxler** [comment]
I would like to reopen this issue...

Following your link on Stackoverflow I was able to install tidyplots by adding the devtools and Cairo packages. But now following your vignette instructions, when I try the command line: study %>% tidyplot(x = treatment, y = score)
I get the following error: Error in ggplot2::scale_y_continuous(name = title, breaks = breaks, labels = labels, :
unused argument (transform = transform)
I am using the 3.4.1 version of ggplot2

If you want to reproduce the error you may use my Dockerfile that I used to run Rstudio:

FROM rocker/rstudio:4.2.2

ARG bioc_ver=3.16

RUN apt-get clean all &&
apt-get update &&
apt-get upgrade -y &&
apt-get install -y
libhdf5-dev
libcurl4-gnutls-dev
libssl-dev
libxml2-dev
libpng-dev
libxt-dev
zlib1g-dev
libbz2-dev
liblzma-dev
libglpk40
libgit2-dev
libcairo2-dev
libjpeg-dev
libtiff-dev
libglib2.0-dev
&& apt-get clean all &&
apt-get purge &&
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
Verify Cairo installation

RUN R -e "capabilities()[['cairo']]"

RUN Rscript -e "install.packages(c('rmarkdown', 'tidyverse', 'workflowr', 'BiocManager', 'dplyr', 'gplots', 'devtools'));"

RUN Rscript -e "BiocManager::install(version = '${bioc_ver}')"
RUN R -e 'BiocManager::install(ask = F)' && R -e 'BiocManager::install(c("AnnotationForge", "Biobase", "biomaRt", "Biostrings", "DESeq2",
"IRange", ask = F))'
RUN R -e 'devtools::install_github("jbengler/tidyplots", ask = F)'

COPY --chown=rstudio:rstudio Rprofile /home/rstudio/.Rprofile

WORKDIR /home/rstudio

**Comment by jbengler** [comment]
Could you update to a more recent version of ggplot2? The one you have is nearly 2 years old.

**Comment by m3i-ltroxler** [comment]
When I as for package update, I get the message that all the packages are up to date. Would it be a limitation due to the 4.2.2 R version ?

**Comment by jbengler** [comment]
I looked into the ggplot2 code. The argument `transform` was introduced Dec 14, 2023. This means you need a ggplot2 version more recent than this date.

If I was you, I would update to the most recent R and run `install.packages("tidyverse")`

In case this is for some reason not possible, you could try remove and re-install ggplot2, hoping to get a newer ggplot2 version.

```
remove.packages("ggplot2")
install.packages("ggplot2")
```

Best
Jan
