### ISSUE TITLE
tidyplots PKG is great + quick question ref very small plot sizes in Rstudio Plot Panel

### ISSUE THREAD

**Issue by sfd99** [jbengler/tidyplots#6]
**_Hi Jan,_**

The tidyplots PKG examples
are all easy to use, understand
and really look great.

But, 
when rendered in my Rstudio Plot Panel,
ALL the example plots 
look _really small_ and hard to read,
(... each plot has a lot of white, empty space around it...).

ie:
library(tidyplots)

study %>% 
  tidyplot(x = treatment, y = score, color = treatment) %>% 
  add_mean_bar(alpha = 0.4) %>% 
  add_sem_errorbar() %>% 
  add_data_points_beeswarm()

Is there a way to enlarge the plot size
 in the Rstudio Plot panel? .
 Maybe I'm doing something wrong?...

Thanks! / Danke!
 
**RAY
San Francisco
_using:_
tidyplots PKG v: 0.1.2 ( d/l from CRAN ) 
Ubuntu Linux 20.04
Rstudio 2024.09.1 Build 394 ( very latest version )
R 4.4.2**

**Comment by jbengler** [comment]
Hi @sfd99 

Thank you for using tidyplots!

Unlike ggplot2, tidyplots uses absolute sizes in millimeter (mm) for plot dimensions. The default plot size is 50 mm by 50 mm. This can be quite small depending on the machine you are working on.

There are several ways to address this.

1. In Rstudio you can increase the zoom. `View` > `Zoom In`. Or alternatively `Ctrl` + `+`. However this will also increase the font size in Rstudio.

2. You can increase the size of the tidyplot.

```
study %>%
  tidyplot(x = treatment, y = score, color = treatment, width = 80, height = 80) %>%
  add_mean_bar(alpha = 0.4) %>%
  add_sem_errorbar() %>%
  add_data_points_beeswarm()

# an alternative way
study %>%
  tidyplot(x = treatment, y = score, color = treatment) %>%
  add_mean_bar(alpha = 0.4) %>%
  add_sem_errorbar() %>%
  add_data_points_beeswarm() %>% 
  adjust_size(80, 80)
```

3. You can let the tidyplot fill all available space (ggplot2 default). However with this solution the proportions between font size and plot size will become arbitrary.

```
study %>%
  tidyplot(x = treatment, y = score, color = treatment, width = NA, height = NA) %>%
  add_mean_bar(alpha = 0.4) %>%
  add_sem_errorbar() %>%
  add_data_points_beeswarm()
```

Best
Jan

**Comment by sfd99** [comment]
Thanks, Jan.
Jan, 
All your suggested  solutions do work ok.
_Thanks!_

Wish there was a
 **default plot size setting**
that I could define in advance,
so that all calls to tidyplot() would follow 
those std. plot size values...

Would that meake sense? :-)

**_RAY_**

**Comment by eggrandio** [comment]
I think I have a problem related to this issue. Whenever I visualize or save a plot, I have plenty of white space in the margins of the plot, even if I set the plot size manually:

```tidyplot_test <- 
  input_data %>% 
  tidyplot(x = time, y = area_perc, color = compound, fill = compound, dodge_width = 0) %>%
  add_mean_line() %>%
  add_data_points(alpha = 0.5, shape = 16) %>%
  add_sem_ribbon() %>% 
  adjust_colors(custom_colors) %>% 
  adjust_x_axis_title("Time (h)") %>% 
  adjust_y_axis_title("Area %") %>% 
  adjust_legend_title(element_blank()) %>% 
  adjust_size(150, 100)
  save_plot("./Biotransformation_plot5.png",
            bg = "white",
            dpi = 600,
            units = "cm",
            width = 15,
            height = 10)
```

<img width="352" alt="image" src="https://github.com/user-attachments/assets/59af09bf-ae86-4ed3-940a-b0ff87212c21">

How can I remove all this blank space?

**Comment by eggrandio** [comment]
Hi,

My apologies for the mistake. I was migssing the pipe. Anyways, I still get the blank space in the PNG file when I adjust the size:

```
study %>% 
  tidyplot(x = treatment, y = score, color = treatment) %>% 
  add_data_points() %>% 
  add_sem_errorbar() %>% 
  add_mean_dash() %>% 
  theme_tidyplot() %>% 
  save_plot("./tidyplot_test.png",
            bg = "white",
            dpi = 600,
            units = "cm",
            width = 15,
            height = 10)
```
Gives:
![tidyplot_test](https://github.com/user-attachments/assets/54d1e2f7-0bed-42dd-8273-5b9f399461eb)

It is a minor issue as I can resize them manually for presentations, etc. but it would be nice to control the size of the output when saving (and keeping the scale between text and plot).

**Comment by riosavila** [comment]
To add to the conversation.
in your examples you have very nice pictures with small white borders. How would you say those are created?
do you edit the white space by hand?

**Comment by jbengler** [comment]
Hi @riosavila 

in RMarkdown files I include:

```
knitr::opts_chunk$set(
  fig.align = "center",
  dpi = 300,
  fig.width = 5,
  fig.height = 2.5
)
```

This nicely fits with the 50 x 50 mm default size of tidyplots.
