### ISSUE TITLE
Can not work with 'patchwork' package

### ISSUE THREAD

**Issue by LiangChen3519** [jbengler/tidyplots#8]
Hi, There.
    Wow~~ tidyplots is a great package for sure, and so amazing to use it. One thing suddenly came to my mind was that, is it possible work with patchwork for combining different plots which from different data frames. And I tired a bit, but failed. Kindly ask that Have you considered adding this feature in future versions？ Thank you in advance.

**Comment by jbengler** [comment]
Hi @LiangChen3519 ,

thank you for using tidyplots!

Patchwork should work just fine with tidyplots.

```
library(tidyplots)
library(patchwork)

p1 <- 
  study %>% 
  tidyplot(x = treatment, y = score, color = treatment) %>% 
  add_mean_bar(alpha = 0.4) %>% 
  add_sem_errorbar() %>% 
  add_data_points_beeswarm()

p2 <- 
  energy %>% 
  tidyplot(x = year, y = power, color = energy_source) %>% 
  add_barstack_absolute()

p1 + p2
```

Best
Jan

**Comment by jbengler** [comment]
Unfortunately, this is not possible. You would need to use ggplot2 code for that. For example by using the `add()` function.

https://jbengler.github.io/tidyplots/reference/add.html

**Comment by LiangChen3519** [comment]
> Unfortunately, this is not possible. You would need to use ggplot2 code for that. For example by using the `add()` function.
> 
> https://jbengler.github.io/tidyplots/reference/add.html

Hi, thanks, it works!!!

```{R}
df <- data.frame(dose=c("D0.5", "D1", "D2"),
                len=c(4.2, 10, 29.5))
df %>% 
  tidyplot(x = dose, y = len, color = dose) %>% 
  add(ggplot2::geom_bar(stat = "identity",fill="white"))
```
We get:
![image](https://github.com/user-attachments/assets/f0d31eaf-3dca-4eed-8335-1dda848a8be3)

**Comment by jbengler** [comment]
For sure. However, people can also search closed issues. I would only keep issues open that are unresolved.

**Comment by LiangChen3519** [comment]
Yeah 👍, thank you so much.

**Comment by jbengler** [comment]
**Quick update**

Since patchwork `v1.3.0` combining tidyplots using the patchwork `+` operator stopped working.

This is not related to tidyplots itself but always happens when combining two patchwork objects with absolute dimensions using the `+` operator.

I opened an issue regarding this new behavior: https://github.com/thomasp85/patchwork/issues/417

As a work around, you can do this

```
patchwork::wrap_plots(p1, p2)
```

Best
Jan
